### ISSUE TITLE
Checking Faithfulness of unfolding operation

### ISSUE THREAD

**Issue by mahi045** [raki123/aspmc#4]
I have a question.
I want to know if there is any way to check whether a given unfolding sequence preserves the faithfulness of Tp-unfolding. I am using some unfolding sequences, which are different from the unfolding sequence based on the backdoor computation technique (as employed in the paper). I am happy to share if you want to know.  

Thanks.

**Comment by raki123** [comment]
That sounds very interesting! I would indeed be very curious to hear about your new technique!

Regarding faithfulness: Lemma 12 and Theorem 13 give a sufficient condition, however, it is not necessary and as far as I can see it is probably NP-hard to check.

Checking directly by unfolding the program and checking whether they have the same answer sets (projected to the original atoms) is probably NP-complete too…
However, I could imagine that clingo would be able to check in reasonable time.
My idea would be to merge the original program and the unfolded program (using the variables of the original program as the variables that occur in the unfolded program under negation and duplicating the rest) and to check whether there is an answer set where the duplicated and original variables do not align. 

If you want to discuss further in more detail I would suggest a zoom meeting or similar.

**Comment by mahi045** [comment]
Thanks @raki123. I got my answer. 
I will talk to you to discuss more.
